[workspace]
authors = ["Ryan Volz <ryan.volz@gmail.com>"]
channels = ["conda-forge", "ryanvolz"]
name = "radioconda"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "2025.03.14"

[tasks]

[dependencies]
airspy = "==1.0.10"
airspyhf = "==1.6.8"
bladerf = "==2024.5"
codec2 = "==1.2.0"
digital_rf = "==2.6.14"
ephem = "==4.2.1"
gnuradio = "==3.10.12.0"
gnuradio-adsb = "==0.0.0.20250304.dev+g9645757"
gnuradio-dect2 = "==0.0.0.20250316.dev+g0d973fe"
gnuradio-filerepeater = "==0.0.0.20250304.dev+gec6b386"
gnuradio-foo = "==0.0.0.20250304.dev+g9e0e2"
gnuradio-fosphor = "==0.0.0.20250304.dev+g85a0b8f"
gnuradio-gpredict-doppler = "==0.0.0.20250303.dev+g9473cbf"
gnuradio-ieee802_11 = "==0.0.0.20250915.dev+gbf25796"
gnuradio-ieee802_15_4 = "==3.6.post20250304+g61f4c4a"
gnuradio-inspector = "==0.0.0.20250303.dev+gad6a69e"
gnuradio-iqbalance = "==0.38.3"
gnuradio-iridium = "==1!1.0.0"
gnuradio-isdbt = "==0.0.0.post20250130+g56b2556"
gnuradio-leo = "==1.0.0.post20250214+g8f62b92"
gnuradio-lora_sdr = "==0.0.0.20260105.dev+g862746d"
gnuradio-m2k = "==1.0.0"
gnuradio-osmosdr = "==0.2.6"
gnuradio-paint = "==0.0.0.20250824.dev+gc443e36"
gnuradio-radar = "==0.0.0.20250220.dev+g92adce2"
gnuradio-rds = "==3.10.post20260104+g58facb6"
gnuradio-satellites = "==5.9.0"
gnuradio-tempest = "==0.0.0.post20250210+g9df8206"
gqrx = "==2.17.7"
hackrf = "==2026.1.3"
hamlib-all = "==4.7.0"
inspectrum = "==0.4.0"
ipython = "==9.11.0"
libiio = "==0.26"
libm2k = "==0.9.0"
limesuite = "==23.11.0"
liquid-dsp = "==1.6.0"
matplotlib = "==3.10.8"
mirisdr = "==2.0.0"
m17-cxx-demod = "==2.3.3"
numpy = "==2.4.2"
pandas = "==3.0.1"
pyadi-iio = "==0.0.20"
pyfda = "==0.9.5"
python = "==3.13.12"
rtl-sdr = "==2.0.2"
scipy = "==1.17.1"
soapysdr = "==0.8.1"
soapysdr-module-airspy = "==0.2.0"
soapysdr-module-airspyhf = "==0.2.0"
soapysdr-module-audio = "==0.1.1"
soapysdr-module-bladerf = "==0.4.2"
soapysdr-module-hackrf = "==0.3.4"
soapysdr-module-netsdr = "==0.2.0"
soapysdr-module-lms7 = "==23.11.0"
soapysdr-module-plutosdr = "==0.2.2"
soapysdr-module-redpitaya = "==0.1.1"
soapysdr-module-remote = "==0.5.2"
soapysdr-module-rtlsdr = "==0.3.3"
soapysdr-module-uhd = "==0.4.1"
soapysdr-module-volk-converters = "==0.1.1"
uhd = "==4.9.0.1"

[feature.installer.dependencies]
conda = "==26.1.1"
mamba = "==2.5.0"

[feature.installer.target.win-64.dependencies]
miniforge_console_shortcut = "==3.0"

[feature.build-installer.dependencies]
anaconda-client = "==1.14.1"
conda-build = "==26.1.0"
constructor = "==3.14.0"
patch-ng = "==1.19.0"
requests = "==2.32.5"

[environments]
installer = { features = ["installer"], solve-group = "default" }
default = { solve-group = "default" }
build-installer = { features = ["build-installer"], no-default-feature = true }

[target.linux-64.dependencies]
alsa-plugins = "==1.2.12"
gnss-sdr = "==0.0.20"
gnuradio-funcube = "==3.10.0.rc3"
gnuradio-hermeslite2 = "==1.0.0.0.post20250305+g2e66561"
gnuradio-hpsdr = "==3.10.20250304.dev+g7748cc9"
soapysdr-module-fcdpp = "==0.1.1"

[target.linux-aarch64.dependencies]
alsa-plugins = "==1.2.12"
gnss-sdr = "==0.0.20"
gnuradio-funcube = "==3.10.0.rc3"
gnuradio-hermeslite2 = "==1.0.0.0.post20250305+g2e66561"
gnuradio-hpsdr = "==3.10.20250304.dev+g7748cc9"
soapysdr-module-fcdpp = "==0.1.1"

[target.osx-64.dependencies]
gnss-sdr = "==0.0.20"
gnuradio-hermeslite2 = "==1.0.0.0.post20250305+g2e66561"
gnuradio-hpsdr = "==3.10.20250304.dev+g7748cc9"

[target.osx-arm64.dependencies]
gnss-sdr = "==0.0.20"
gnuradio-hermeslite2 = "==1.0.0.0.post20250305+g2e66561"
gnuradio-hpsdr = "==3.10.20250304.dev+g7748cc9"
